### ISSUE TITLE
Failure during adding parts with faces having no normals

### ISSUE THREAD

**Issue by arkhnchul** [execuc/LCInterlocking#15]
some faces of part surprisingly can exist without associated normal, especially those which created by extruding imported vector artwork, and in this case sort_area_face_common routine fails at face.normalAt() call. Patch with catching of resulting exceptions and test freecad file included.
[fix_faces_without_normal.patch.txt](https://github.com/execuc/LCInterlocking/files/1316101/fix_faces_without_normal.patch.txt)
[hopper_car_test.fcstd.zip](https://github.com/execuc/LCInterlocking/files/1316106/hopper_car_test.fcstd.zip)

**Comment by luzpaz** [comment]
bump

**Comment by execuc** [comment]
Thank you ! I have applied the patch.
