### ISSUE TITLE
Can't see Parameters Tab

### ISSUE THREAD

**Issue by AIWintermuteAI** [execuc/LCInterlocking#20]
I have successfully installed the addon, but after I make a box I press on Tabs and the interface looks different from what the one in YouTube video. I can't see the parameters tab
Windows 10 64-bit FreeCAD 0.17
![2019-01-21](https://user-images.githubusercontent.com/32562299/51455832-55928680-1d86-11e9-89f6-1f5d21ddf5c9.png)

**Comment by execuc** [comment]
Thank you for trying this module.
The videos are based on an older version of the module. I made a short document for each module tool and I would make new video when I could.
In case, it is necessary first to declare the parts with add same part.
