### ISSUE TITLE
Cross join - disable dog bone hole

### ISSUE THREAD

**Issue by Dlaha** [execuc/LCInterlocking#21]
I'm unable to figure out how to disable dog bone hole generation for cross join. Is that even possible?

**Comment by execuc** [comment]
Hello,
Actually, it's not possible at the moment, sorry.
I'll add the option of that I could. Thank you for trying this module.

**Comment by execuc** [comment]
It was a mistake during refactor, sorry ! 
Now, I have restored dog bones and node options.
