### ISSUE TITLE
This FC addon needs a legit svg icon for the FC AddonManager

### ISSUE THREAD

**Issue by luzpaz** [execuc/LCInterlocking#27]
We bundle the FreeCAD-addons workbench/addons SVG icons within FC. Once you add it to this repo, I'll copy it in to master.

**Comment by execuc** [comment]
Thanks for the integration of this module in freecad.
To understand what I need to do, I have to make an icon for this module in SVG to replace the 16x16 xpm icon ?

**Comment by luzpaz** [comment]
not replace just have an svg version as well

**Comment by execuc** [comment]
I added icon at base directory ("addon_icon.svg"). Could you tell me if that's okay ?

**Comment by luzpaz** [comment]
It looks good but the size of the file is pretty large. Take for example other workbench icons in:  
https://github.com/FreeCAD/FreeCAD/tree/master/src/Mod/AddonManager/Resources/icons

**Comment by execuc** [comment]
OK. I made a smaller one.
