### ISSUE TITLE
Adding same parts fails due to thickness unequality

### ISSUE THREAD

**Issue by arkhnchul** [execuc/LCInterlocking#3]
some parts fails to be added as "same parts" with message "_partname_ does not have the same thickness", even when thicknesses are equal in cad. This happens due to strong equality check between floats in append_link method of PartsList (partmat.py). Comparing absolute difference with some reasonable delta value, 0.001 or so, is more reliable here.
for example two parts in attached file, with thicknesses differ by 8.881784197e-16

[test1_assy2.zip](https://github.com/execuc/LCInterlocking/files/472084/test1_assy2.zip)

[thicknesses_unequality.patch.txt](https://github.com/execuc/LCInterlocking/files/472106/thicknesses_unequality.patch.txt)

**Comment by execuc** [comment]
Ok, I fix it using a function defined in other file. Default tolerance is 10e-6 in this function but if issue is still present I will set to 0.001.

**Comment by arkhnchul** [comment]
as far as i see, issue isn't showing anymore.

**Comment by execuc** [comment]
Ok, thank you for the fix and the test.
