### ISSUE TITLE
Automatically remove unnecessary lines on export

### ISSUE THREAD

**Issue by arkhnchul** [execuc/LCInterlocking#4]
It is possible to eliminate later external postprocessing after exporting svg by preliminary refinement of exported parts via .removeSplitter() method of Shape objects ("Part -> Refine shape" menu item of Part workbench). Small demonstration patch attached.
[splitter_auto_removal.patch.txt](https://github.com/execuc/LCInterlocking/files/523211/splitter_auto_removal.patch.txt)

**Comment by execuc** [comment]
Ok, it is a good info. I missed this ".removeSplitter()" method. I will test it and integrate it. Thank you.

**Comment by execuc** [comment]
After small tests, I think it works so I integrate it. Thank you very much !
