### ISSUE TITLE
Slot width tolerance wrong way around

### ISSUE THREAD

**Issue by Tectu** [execuc/LCInterlocking#44]
I'm experiencing issues with the `Slot width tolerance` setting of the tab feature.

It seems like the the `slot width tolerance` is applied "the wrong way around". Instead of the slot being wider than the tab (or the tab shorter than the slot) I end up with tabs that are too wide. After applying the operation the tabs are made wider by the amount specified in the `slot width tolerance` parameter.

I imagined that specifying a negative slot width tolerance would be a sufficient workaround but the field only accepts positive numbers.

I'm experiencing this issue with FreeCAD 0.18.4 and 0.19.22.

Am I missing something / doing something wrong?

**Comment by execuc** [comment]
Hello, I did a test and it seems to work as you specify it. When I increase the "Slot width tolerance" parameter of the part, the slot width increases while the tab remains the same. Attached is a screenshot with a high value (5mm).

![tab_slot_tolerance](https://user-images.githubusercontent.com/7314048/95358735-aaaf5c80-08c9-11eb-8bbf-4f78e6d32c12.png)

There is the opposite behavior when I increase the "laser beam diameter" parameter, wouldn't there be a shift in the parameters (from the interface) ?

**Comment by Tectu** [comment]
I can confirm that this is working as intended. The issue I described arises when the `slot width tolerance` is smaller than the `laser beam diameter` value.
